<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/27 0027
 * Time: 10:24
 */
namespace app\weke\controller;
use app\weke\model\ExchangeOrder;
class MyExchange extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //验证登录
        $this->checkLogin();
    }

    public function myExchange()
    {
        $acerType = ['0'=>'全部','1'=>'虚拟类','2'=>'实物类'];
        $user_id = $this->user_id;
        //接受类别，0为全部
        $typeNow = input('acer_type');
        if(empty($typeNow)){
            $typeNow = 0;
        }
        $user_acer = $this->user_info ? $this->user_info['member_acer'] : 0;
        $acerGoods = ExchangeOrder::with('productAcer')
            ->where('member_id','eq',$user_id)
            ->where('product_type','eq',$typeNow)
            ->select();

        return [
            'status'  => '1',
            'message' => '请求成功',
            'data' => [
                'acer_type' => $acerType,
                'type_now' => $typeNow,
                'acer_goods' => $acerGoods
            ]
        ];
    }
}