<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/11/3
 * Time: 15:06
 */
namespace app\vke\controller;
use app\vke\controller\Common;

class Message extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    /**
     * 获得当前用户的信息
     */
    public function getMessage()
    {
        $user_id = $this->user_id;
        //获得该用户的消息列表
        $messageList = model('Message')->getMessageList($user_id);
        foreach($messageList as $key => $value){
            $time = date("m-d H:i",strtotime($value['add_time']));
            $messageList[$key]['add_time'] = $time;
        }
        $result = [
            'data' => [
                'message_list' => $messageList
            ]
        ];
        return resultArray($result);
    }
}