<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/11/3
 * Time: 15:06
 */
namespace app\vke\controller;
use app\vke\controller\Common;
use think\Request;

class Message extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    /**
     * 获得当前用户的信息
     */
    public function getMessage()
    {
        $user_id = $this->user_id;
        //获得该用户的消息列表
        $messageList = model('AdminMessage')->getMessageList($user_id);
        foreach($messageList as $key => $value){
            $time = date("m-d H:i",strtotime($value['add_time']));
            $messageList[$key]['add_time'] = $time;
        }
        $result = [
            'data' => [
                'message_list' => $messageList
            ]
        ];
        return resultArray($result);
    }


    /**
     * 清空消息列表 - 20171114
     */
    public function delMessage()
    {
        $request = Request::instance();
        $user_id = $this->user_id;

            //执行删除
            $map = [
                'member_id' => $user_id
            ];

            $data = [
                'is_del' => 2,
                'del_time' => date('Y-m-d H:i:s',time())
            ];

            $result_del = model('AdminMessage')->where($map)->update($data);

            if($result_del){
               $result = [
                   'data' => [
                       'message' => '删除成功'
                   ]
               ];
            }else{
                $result = [
                    'error' => '删除失败'
                ];
            }
            return resultArray($result);

    }
}