<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/11/6
 * Time: 10:43
 */
namespace app\vke\controller;
use app\vke\controller\Common;
use think\Request;


class Order extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this -> checkLogin();
    }

    /**
     * 添加订单页面
     */
    public function addOrderPage()
    {
        if(Request::instance()->isGet()){
            $help = model('Help')->getHelpInfo(2);
            $result = [
                'data' => [
                    'order_help' => $help
                ]
            ];
        }
        elseif(Request::instance()->isPost()){
            $user_id = $this->user_id;
            //接收订单号
            $order_num = input('order_num');
            $validate = auto_validate('Order',['order_num'=>$order_num]);
            if($validate){
                return $validate;
            }

            //验证该订单状态  //TODO   验证订单是否真实有效
            $order_status = true;

            if($order_status){

            }else{
                return resultArray(['error'=>'无效的订单']);
            }

            //查询订单号在数据库中是否存在
            if(model('Order')->where(['order_num'=>$order_num])->find()){
                return resultArray(['error'=>'请勿重复添加']);
            }

            //查询添加订单默认的元宝数量
            $acer_num = db('acer_reward')->where(['type'=>1,'status'=>1])->value('acer_number');

            //调用接口获得商品的num_iid //TODO 调用淘宝客获取订单信息接口
            $num_iid = 1;
            $data = [
                'order_num' => $order_num,
                'member_id' => $user_id,
                'num_iid' => $num_iid,
                'back_status' => 2,
                'back_acer' => $acer_num ? $acer_num : 0
            ];
            $model = model('Order');
            $model-> data($data);
            if($model->save()){
                $result = [
                    'data' => [
                        'message' => '订单添加成功'
                    ]
                ];

                //向后台发送系统通知
                $message = [
                    'type' => '2',
                    'title' => '返利订单待审核通知',
                    'msg' => '您有新的返利订单待审核，请点击前往处理。订单号为'.$order_num
                ];
                sendMessage($message);
            }
            else{
                $result = [
                    'error' => '订单添加失败'
                ];
            }
        }
        return resultArray($result);
    }


    /**
     * 我的订单*20171106
     */
    public function myOrder()
    {
        $map = [];
        $request = Request::instance();
        $user_id = $this->user_id;
        $back_status = $request->post('back_status');

            if($back_status == 3){ //已返订单
                $back_status = 1;
                $map['o.back_status'] = $back_status;
            }
            elseif($back_status == 2){ //未返订单
                $map['o.back_status'] = $back_status;
            }

        $map['o.member_id'] = $user_id;
        //根据user_id查询订单
        $orderList = model('Order')->getMyOrder($map);
        $result = [
            'data'=>[
                'order_list' => $orderList
            ]
        ];
        return resultArray($result);
    }
}