<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/11/7
 * Time: 11:06
 */

namespace app\vke\controller;
use app\vke\controller\Common;

class Search extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    /**
     * 搜索页面-搜索历史
     */
    public function searchPage()
    {
        $user_id = $this->user_id;
        //根据用户id查询搜索历史
        $searchHistory = model('SearchHistory')->getSearchHistory($user_id);



        $result = [
            'data' => [
                'history' => $searchHistory,
            ]
        ];

        return resultArray($result);
    }
    /**
     * 搜索页面-默认搜索项
     */
    public function searchDefault()
    {
        //默认搜索词
        $defaultWords = model('SearchKeywords')->getDefaultWords();
        $rand = mt_rand(0, $defaultWords['count'] - 1);
        $result = [
            'data' => [
                'default' => $defaultWords['words'][$rand]
            ]
        ];
        return resultArray($result);
    }


    /**
     * 搜索页面-热门推荐
     */
    public function searchPageHot()
    {
        //查询热门推荐搜索
        $hotSearch = model('SearchHistory')->getHotSearch();
        $result = [
            'data' => [
                'hot' => $hotSearch
            ]
        ];
        return resultArray($result);
    }

    /**
     * 执行搜索
     */
    public function doSearch()
    {
        $user_id = $this->user_id;
        //接收搜索关键词
        $keywords = input('keywords');
        if(empty($keywords)){
            return resultArray(['error'=>'请输入搜索内容']);
        }
        //将搜索内容存入数据库,根据会员id和搜索内容查询该用户是否已经有过搜索
        $search_result = db('search_history')->where(['member_id'=>$user_id,'keywords'=>$keywords])->value('id');
        $model = model('SearchHistory');
        if($search_result){
            $model->where('id',$search_result)->setInc('number',1);
        }else{
            $data = [
                'member_id' => $user_id,
                'keywords' => $keywords,
                'number' => 1
            ];
            $model->data($data);
            $model->save();

        }

        //根据搜索关键词搜索产品
        $productList = model('Product')->getProductListByKeywords($keywords);
        $result = [
            'data' => [
                'product_list' => $productList
            ]
        ];

        return resultArray($result);
    }

    /**
     * 智搜页面
     */
    public function AIsearch()
    {
        //查询智搜页下的导航图
        $banner = model('Banner')->getBannerList(10)[0];
        //默认搜索词
        $defaultWords = model('SearchKeywords')->getDefaultWords();
        $rand = mt_rand(0,$defaultWords['count']-1);
        $result = [
            'data' => [
                'banner' => $banner,
                'default' => $defaultWords['words'][$rand]
            ]
        ];

        return resultArray($result);
    }
}