<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/11/6
 * Time: 16:19
 */

namespace app\vke\controller;
use app\vke\controller\Common;
use think\Request;
use app\vke\model\MemberEvaluate;
use app\vke\model\Order;


class Shareorder extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    /**
     * 晒单
     * @return array|\think\response\Json
     */
    public function shareOrder()
    {
        if(Request::instance()->isPost()){
            $user_id = $this->user_id;
            $data = [
                'evaluate_detail' => input('evaluate'),
                'evaluate_url' => input('images',""),
                'order_num' => input('order_num')
            ];

            $validate = validate('Evaluate');
            if(!$validate->check($data)){
                return resultArray(['error'=>$validate->getError()]);
            }
            //验证该订单号是否存在

            if(!Order::get(['order_num'=>$data['order_num']])){
                return resultArray(['error'=>'该订单不存在']);
            }

            //同一商品同一用户只能晒单一次
            if(MemberEvaluate::get(['order_num'=>$data['order_num'],'member_id'=>$user_id,'examine_status'=>1])){
                return resultArray(['error'=>'请勿重复晒单']);
            }
            //查询晒单默认的奖励元宝数
            $acer_number = db('acer_reward')->where(['type'=>2,'status'=>1])->value('acer_number');

            //添加到数据库
            $data['member_id'] = $user_id;
            $data['examine_status'] = 2;
            $data['acer_num'] = $acer_number;

            $model = new MemberEvaluate;
            $model -> data($data);
            if($model->save()){
                $result = [
                    'data' => [
                        'message' => '晒单成功,请等待审核'
                    ]
                ];
            }else{
                $result = [
                    'error' => '晒单失败'
                ];
            }
            return resultArray($result);

        }
    }


    /**
     * 我的晒单
     */
    public function myShareOrder()
    {
        $user_id = $this->user_id;
        //根据会员id查询晒单情况
        $myShareOrder = model('MemberEvaluate')->myShareOrder($user_id);
        if(!empty($myShareOrder)){
            foreach($myShareOrder as $key => $value){
                $url = explode(',',$value['evaluate_url']);
                $evaluate_url = [];
                foreach($url as $k => $val){
                    $evaluate_url[]['image'] = $val;
                }
                $myShareOrder[$key]['evaluate_url'] = $evaluate_url;
                $myShareOrder[$key]['create_time'] = substr($value['create_time'],0,10);
            }

        }
        $result = [
            'data' => [
                'my_order' => $myShareOrder
            ]
        ];
        return resultArray($result);
    }

    /**
     * 晒单广场
     */
    public function orderSquare()
    {
        $orderSpuare = model('MemberEvaluate')->getOrderSquare();
        if(!empty($orderSpuare)){
            foreach($orderSpuare as $key => $value){
                $url = explode(',',$value['evaluate_url']);
                $evaluate_url = [];
                foreach($url as $k => $val){
                    $evaluate_url[]['image'] = $val;
                }
                $orderSpuare[$key]['evaluate_url'] = $evaluate_url;
                $orderSpuare[$key]['create_time'] = substr($value['create_time'],0,10);
            }
        }

        $result = [
            'data' => [
                'order_square' => $orderSpuare
            ]
        ];

        return resultArray($result);
    }
}